//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Deck;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Type : SmartEnum<Type> {
    public static readonly Type AdvancedDeck = new(nameof(AdvancedDeck), 0);
    public static readonly Type AdvancedPack = new(nameof(AdvancedPack), 1);
    public static readonly Type ArchenemyDeck = new(nameof(ArchenemyDeck), 2);
    public static readonly Type BasicDeck = new(nameof(BasicDeck), 3);
    public static readonly Type BrawlDeck = new(nameof(BrawlDeck), 4);
    public static readonly Type ChallengerDeck = new(nameof(ChallengerDeck), 5);
    public static readonly Type ClashPack = new(nameof(ClashPack), 6);
    public static readonly Type CommanderDeck = new(nameof(CommanderDeck), 7);
    public static readonly Type DuelDeck = new(nameof(DuelDeck), 8);
    public static readonly Type DuelOfThePlaneswalkersDeck = new(nameof(DuelOfThePlaneswalkersDeck), 9);
    public static readonly Type EventDeck = new(nameof(EventDeck), 10);
    public static readonly Type GameNightDeck = new(nameof(GameNightDeck), 11);
    public static readonly Type GuildKit = new(nameof(GuildKit), 12);
    public static readonly Type Halfdeck = new(nameof(Halfdeck), 13);
    public static readonly Type IntroPack = new(nameof(IntroPack), 14);
    public static readonly Type Jumpstart = new(nameof(Jumpstart), 15);
    public static readonly Type MTGOThemeDeck = new(nameof(MTGOThemeDeck), 16);
    public static readonly Type PioneerChallengerDeck = new(nameof(PioneerChallengerDeck), 17);
    public static readonly Type PlanechaseDeck = new(nameof(PlanechaseDeck), 18);
    public static readonly Type PlaneswalkerDeck = new(nameof(PlaneswalkerDeck), 19);
    public static readonly Type PremiumDeck = new(nameof(PremiumDeck), 20);
    public static readonly Type SpellslingerStarterKit = new(nameof(SpellslingerStarterKit), 21);
    public static readonly Type StarterDeck = new(nameof(StarterDeck), 22);
    public static readonly Type ThemeDeck = new(nameof(ThemeDeck), 23);
    public static readonly Type WelcomeDeck = new(nameof(WelcomeDeck), 24);
    public static readonly Type WorldChampionshipDecks = new(nameof(WorldChampionshipDecks), 25);
    public Type(string name, int value) : base(name, value){}
}
