//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Card;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Availability : SmartEnum<Availability> {
    public static readonly Availability Arena = new(nameof(Arena), 0);
    public static readonly Availability Dreamcast = new(nameof(Dreamcast), 1);
    public static readonly Availability Mtgo = new(nameof(Mtgo), 2);
    public static readonly Availability Paper = new(nameof(Paper), 3);
    public static readonly Availability Shandalar = new(nameof(Shandalar), 4);
    public Availability(string name, int value) : base(name, value){}
}
