//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Card;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class BoosterTypes : SmartEnum<BoosterTypes> {
    public static readonly BoosterTypes Deck = new(nameof(Deck), 0);
    public static readonly BoosterTypes Draft = new(nameof(Draft), 1);
    public BoosterTypes(string name, int value) : base(name, value){}
}
