//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Card;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class BorderColor : SmartEnum<BorderColor> {
    public static readonly BorderColor Black = new(nameof(Black), 0);
    public static readonly BorderColor Borderless = new(nameof(Borderless), 1);
    public static readonly BorderColor Gold = new(nameof(Gold), 2);
    public static readonly BorderColor Silver = new(nameof(Silver), 3);
    public static readonly BorderColor White = new(nameof(White), 4);
    public BorderColor(string name, int value) : base(name, value){}
}
