//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Card;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class ColorIdentity : SmartEnum<ColorIdentity> {
    public static readonly ColorIdentity B = new(nameof(B), 0);
    public static readonly ColorIdentity G = new(nameof(G), 1);
    public static readonly ColorIdentity R = new(nameof(R), 2);
    public static readonly ColorIdentity U = new(nameof(U), 3);
    public static readonly ColorIdentity W = new(nameof(W), 4);
    public ColorIdentity(string name, int value) : base(name, value){}
}
