//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Card;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Colors : SmartEnum<Colors> {
    public static readonly Colors B = new(nameof(B), 0);
    public static readonly Colors G = new(nameof(G), 1);
    public static readonly Colors R = new(nameof(R), 2);
    public static readonly Colors U = new(nameof(U), 3);
    public static readonly Colors W = new(nameof(W), 4);
    public Colors(string name, int value) : base(name, value){}
}
