//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Card;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class DuelDeck : SmartEnum<DuelDeck> {
    public static readonly DuelDeck A = new(nameof(A), 0);
    public static readonly DuelDeck B = new(nameof(B), 1);
    public DuelDeck(string name, int value) : base(name, value){}
}
