//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Card;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class FrameEffects : SmartEnum<FrameEffects> {
    public static readonly FrameEffects Colorshifted = new(nameof(Colorshifted), 0);
    public static readonly FrameEffects Companion = new(nameof(Companion), 1);
    public static readonly FrameEffects Compasslanddfc = new(nameof(Compasslanddfc), 2);
    public static readonly FrameEffects Convertdfc = new(nameof(Convertdfc), 3);
    public static readonly FrameEffects Devoid = new(nameof(Devoid), 4);
    public static readonly FrameEffects Draft = new(nameof(Draft), 5);
    public static readonly FrameEffects Etched = new(nameof(Etched), 6);
    public static readonly FrameEffects Extendedart = new(nameof(Extendedart), 7);
    public static readonly FrameEffects Fandfc = new(nameof(Fandfc), 8);
    public static readonly FrameEffects Fullart = new(nameof(Fullart), 9);
    public static readonly FrameEffects Inverted = new(nameof(Inverted), 10);
    public static readonly FrameEffects Legendary = new(nameof(Legendary), 11);
    public static readonly FrameEffects Lesson = new(nameof(Lesson), 12);
    public static readonly FrameEffects Miracle = new(nameof(Miracle), 13);
    public static readonly FrameEffects Mooneldrazidfc = new(nameof(Mooneldrazidfc), 14);
    public static readonly FrameEffects Nyxtouched = new(nameof(Nyxtouched), 15);
    public static readonly FrameEffects Originpwdfc = new(nameof(Originpwdfc), 16);
    public static readonly FrameEffects Shatteredglass = new(nameof(Shatteredglass), 17);
    public static readonly FrameEffects Showcase = new(nameof(Showcase), 18);
    public static readonly FrameEffects Snow = new(nameof(Snow), 19);
    public static readonly FrameEffects Storyspotlight = new(nameof(Storyspotlight), 20);
    public static readonly FrameEffects Sunmoondfc = new(nameof(Sunmoondfc), 21);
    public static readonly FrameEffects Textless = new(nameof(Textless), 22);
    public static readonly FrameEffects Tombstone = new(nameof(Tombstone), 23);
    public static readonly FrameEffects Upsidedowndfc = new(nameof(Upsidedowndfc), 24);
    public static readonly FrameEffects Waxingandwaningmoondfc = new(nameof(Waxingandwaningmoondfc), 25);
    public FrameEffects(string name, int value) : base(name, value){}
}
