//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Card;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class FrameVersion : SmartEnum<FrameVersion> {
    public static readonly FrameVersion Frame1993 = new(nameof(Frame1993), 0);
    public static readonly FrameVersion Frame1997 = new(nameof(Frame1997), 1);
    public static readonly FrameVersion Frame2003 = new(nameof(Frame2003), 2);
    public static readonly FrameVersion Frame2015 = new(nameof(Frame2015), 3);
    public static readonly FrameVersion Future = new(nameof(Future), 4);
    public FrameVersion(string name, int value) : base(name, value){}
}
