//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Card;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Layout : SmartEnum<Layout> {
    public static readonly Layout Adventure = new(nameof(Adventure), 0);
    public static readonly Layout Aftermath = new(nameof(Aftermath), 1);
    public static readonly Layout ArtSeries = new(nameof(ArtSeries), 2);
    public static readonly Layout Augment = new(nameof(Augment), 3);
    public static readonly Layout Class = new(nameof(Class), 4);
    public static readonly Layout DoubleFacedToken = new(nameof(DoubleFacedToken), 5);
    public static readonly Layout Emblem = new(nameof(Emblem), 6);
    public static readonly Layout Flip = new(nameof(Flip), 7);
    public static readonly Layout Host = new(nameof(Host), 8);
    public static readonly Layout Leveler = new(nameof(Leveler), 9);
    public static readonly Layout Meld = new(nameof(Meld), 10);
    public static readonly Layout ModalDfc = new(nameof(ModalDfc), 11);
    public static readonly Layout Normal = new(nameof(Normal), 12);
    public static readonly Layout Planar = new(nameof(Planar), 13);
    public static readonly Layout ReversibleCard = new(nameof(ReversibleCard), 14);
    public static readonly Layout Saga = new(nameof(Saga), 15);
    public static readonly Layout Scheme = new(nameof(Scheme), 16);
    public static readonly Layout Split = new(nameof(Split), 17);
    public static readonly Layout Token = new(nameof(Token), 18);
    public static readonly Layout Transform = new(nameof(Transform), 19);
    public static readonly Layout Vanguard = new(nameof(Vanguard), 20);
    public Layout(string name, int value) : base(name, value){}
}
