//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Card;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class PromoTypes : SmartEnum<PromoTypes> {
    public static readonly PromoTypes Arenaleague = new(nameof(Arenaleague), 0);
    public static readonly PromoTypes Boosterfun = new(nameof(Boosterfun), 1);
    public static readonly PromoTypes Boxtopper = new(nameof(Boxtopper), 2);
    public static readonly PromoTypes Brawldeck = new(nameof(Brawldeck), 3);
    public static readonly PromoTypes Bringafriend = new(nameof(Bringafriend), 4);
    public static readonly PromoTypes Bundle = new(nameof(Bundle), 5);
    public static readonly PromoTypes Buyabox = new(nameof(Buyabox), 6);
    public static readonly PromoTypes Convention = new(nameof(Convention), 7);
    public static readonly PromoTypes Datestamped = new(nameof(Datestamped), 8);
    public static readonly PromoTypes Draculaseries = new(nameof(Draculaseries), 9);
    public static readonly PromoTypes Draftweekend = new(nameof(Draftweekend), 10);
    public static readonly PromoTypes Duels = new(nameof(Duels), 11);
    public static readonly PromoTypes Event = new(nameof(Event), 12);
    public static readonly PromoTypes Fnm = new(nameof(Fnm), 13);
    public static readonly PromoTypes Galaxyfoil = new(nameof(Galaxyfoil), 14);
    public static readonly PromoTypes Gameday = new(nameof(Gameday), 15);
    public static readonly PromoTypes Gateway = new(nameof(Gateway), 16);
    public static readonly PromoTypes Giftbox = new(nameof(Giftbox), 17);
    public static readonly PromoTypes Gilded = new(nameof(Gilded), 18);
    public static readonly PromoTypes Godzillaseries = new(nameof(Godzillaseries), 19);
    public static readonly PromoTypes Instore = new(nameof(Instore), 20);
    public static readonly PromoTypes Intropack = new(nameof(Intropack), 21);
    public static readonly PromoTypes Jpwalker = new(nameof(Jpwalker), 22);
    public static readonly PromoTypes Judgegift = new(nameof(Judgegift), 23);
    public static readonly PromoTypes League = new(nameof(League), 24);
    public static readonly PromoTypes Mediainsert = new(nameof(Mediainsert), 25);
    public static readonly PromoTypes Neonink = new(nameof(Neonink), 26);
    public static readonly PromoTypes Openhouse = new(nameof(Openhouse), 27);
    public static readonly PromoTypes Planeswalkerstamped = new(nameof(Planeswalkerstamped), 28);
    public static readonly PromoTypes Playerrewards = new(nameof(Playerrewards), 29);
    public static readonly PromoTypes Playpromo = new(nameof(Playpromo), 30);
    public static readonly PromoTypes Premiereshop = new(nameof(Premiereshop), 31);
    public static readonly PromoTypes Prerelease = new(nameof(Prerelease), 32);
    public static readonly PromoTypes Promopack = new(nameof(Promopack), 33);
    public static readonly PromoTypes Release = new(nameof(Release), 34);
    public static readonly PromoTypes Schinesealtart = new(nameof(Schinesealtart), 35);
    public static readonly PromoTypes Setpromo = new(nameof(Setpromo), 36);
    public static readonly PromoTypes Stamped = new(nameof(Stamped), 37);
    public static readonly PromoTypes Surgefoil = new(nameof(Surgefoil), 38);
    public static readonly PromoTypes Textured = new(nameof(Textured), 39);
    public static readonly PromoTypes Themepack = new(nameof(Themepack), 40);
    public static readonly PromoTypes Thick = new(nameof(Thick), 41);
    public static readonly PromoTypes Tourney = new(nameof(Tourney), 42);
    public static readonly PromoTypes Wizardsplaynetwork = new(nameof(Wizardsplaynetwork), 43);
    public PromoTypes(string name, int value) : base(name, value){}
}
