//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Card;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Rarity : SmartEnum<Rarity> {
    public static readonly Rarity Bonus = new(nameof(Bonus), 0);
    public static readonly Rarity Common = new(nameof(Common), 1);
    public static readonly Rarity Mythic = new(nameof(Mythic), 2);
    public static readonly Rarity Rare = new(nameof(Rare), 3);
    public static readonly Rarity Special = new(nameof(Special), 4);
    public static readonly Rarity Uncommon = new(nameof(Uncommon), 5);
    public Rarity(string name, int value) : base(name, value){}
}
