//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Card;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class SecurityStamp : SmartEnum<SecurityStamp> {
    public static readonly SecurityStamp Acorn = new(nameof(Acorn), 0);
    public static readonly SecurityStamp Arena = new(nameof(Arena), 1);
    public static readonly SecurityStamp Oval = new(nameof(Oval), 2);
    public static readonly SecurityStamp Triangle = new(nameof(Triangle), 3);
    public SecurityStamp(string name, int value) : base(name, value){}
}
