//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Card;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Supertypes : SmartEnum<Supertypes> {
    public static readonly Supertypes Basic = new(nameof(Basic), 0);
    public static readonly Supertypes Host = new(nameof(Host), 1);
    public static readonly Supertypes Legendary = new(nameof(Legendary), 2);
    public static readonly Supertypes Ongoing = new(nameof(Ongoing), 3);
    public static readonly Supertypes Snow = new(nameof(Snow), 4);
    public static readonly Supertypes World = new(nameof(World), 5);
    public Supertypes(string name, int value) : base(name, value){}
}
