//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Card;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Types : SmartEnum<Types> {
    public static readonly Types Artifact = new(nameof(Artifact), 0);
    public static readonly Types Card = new(nameof(Card), 1);
    public static readonly Types Conspiracy = new(nameof(Conspiracy), 2);
    public static readonly Types Creature = new(nameof(Creature), 3);
    public static readonly Types Dragon = new(nameof(Dragon), 4);
    public static readonly Types Dungeon = new(nameof(Dungeon), 5);
    public static readonly Types Eaturecray = new(nameof(Eaturecray), 6);
    public static readonly Types Elemental = new(nameof(Elemental), 7);
    public static readonly Types Elite = new(nameof(Elite), 8);
    public static readonly Types Emblem = new(nameof(Emblem), 9);
    public static readonly Types Enchantment = new(nameof(Enchantment), 10);
    public static readonly Types Ever = new(nameof(Ever), 11);
    public static readonly Types Goblin = new(nameof(Goblin), 12);
    public static readonly Types Hero = new(nameof(Hero), 13);
    public static readonly Types Instant = new(nameof(Instant), 14);
    public static readonly Types Jaguar = new(nameof(Jaguar), 15);
    public static readonly Types Knights = new(nameof(Knights), 16);
    public static readonly Types Land = new(nameof(Land), 17);
    public static readonly Types Phenomenon = new(nameof(Phenomenon), 18);
    public static readonly Types Plane = new(nameof(Plane), 19);
    public static readonly Types Planeswalker = new(nameof(Planeswalker), 20);
    public static readonly Types Scariest = new(nameof(Scariest), 21);
    public static readonly Types Scheme = new(nameof(Scheme), 22);
    public static readonly Types See = new(nameof(See), 23);
    public static readonly Types Sorcery = new(nameof(Sorcery), 24);
    public static readonly Types Sticker = new(nameof(Sticker), 25);
    public static readonly Types Summon = new(nameof(Summon), 26);
    public static readonly Types Token = new(nameof(Token), 27);
    public static readonly Types Tribal = new(nameof(Tribal), 28);
    public static readonly Types Vanguard = new(nameof(Vanguard), 29);
    public static readonly Types Wolf = new(nameof(Wolf), 30);
    public static readonly Types Youll = new(nameof(Youll), 31);
    public Types(string name, int value) : base(name, value){}
}
