//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Card;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Types : SmartEnum<Types> {
    public static readonly Types __ = new(nameof(__), 0);
    public static readonly Types Artifact = new(nameof(Artifact), 1);
    public static readonly Types Card = new(nameof(Card), 2);
    public static readonly Types Conspiracy = new(nameof(Conspiracy), 3);
    public static readonly Types Construct = new(nameof(Construct), 4);
    public static readonly Types Creature = new(nameof(Creature), 5);
    public static readonly Types Dragon = new(nameof(Dragon), 6);
    public static readonly Types Dungeon = new(nameof(Dungeon), 7);
    public static readonly Types Eaturecray = new(nameof(Eaturecray), 8);
    public static readonly Types Elemental = new(nameof(Elemental), 9);
    public static readonly Types Elite = new(nameof(Elite), 10);
    public static readonly Types Emblem = new(nameof(Emblem), 11);
    public static readonly Types Enchantment = new(nameof(Enchantment), 12);
    public static readonly Types Ever = new(nameof(Ever), 13);
    public static readonly Types Goblin = new(nameof(Goblin), 14);
    public static readonly Types Hero = new(nameof(Hero), 15);
    public static readonly Types Horror = new(nameof(Horror), 16);
    public static readonly Types Instant = new(nameof(Instant), 17);
    public static readonly Types Jaguar = new(nameof(Jaguar), 18);
    public static readonly Types Knights = new(nameof(Knights), 19);
    public static readonly Types Land = new(nameof(Land), 20);
    public static readonly Types Phenomenon = new(nameof(Phenomenon), 21);
    public static readonly Types Phyrexian = new(nameof(Phyrexian), 22);
    public static readonly Types Plane = new(nameof(Plane), 23);
    public static readonly Types Planeswalker = new(nameof(Planeswalker), 24);
    public static readonly Types Scariest = new(nameof(Scariest), 25);
    public static readonly Types Scheme = new(nameof(Scheme), 26);
    public static readonly Types See = new(nameof(See), 27);
    public static readonly Types Sorcery = new(nameof(Sorcery), 28);
    public static readonly Types Stickers = new(nameof(Stickers), 29);
    public static readonly Types Summon = new(nameof(Summon), 30);
    public static readonly Types Token = new(nameof(Token), 31);
    public static readonly Types Tribal = new(nameof(Tribal), 32);
    public static readonly Types Vanguard = new(nameof(Vanguard), 33);
    public static readonly Types Wolf = new(nameof(Wolf), 34);
    public static readonly Types Youll = new(nameof(Youll), 35);
    public Types(string name, int value) : base(name, value){}
}
