//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.ForeignData;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Language : SmartEnum<Language> {
    public static readonly Language AncientGreek = new(nameof(AncientGreek), 0);
    public static readonly Language Arabic = new(nameof(Arabic), 1);
    public static readonly Language ChineseSimplified = new(nameof(ChineseSimplified), 2);
    public static readonly Language ChineseTraditional = new(nameof(ChineseTraditional), 3);
    public static readonly Language French = new(nameof(French), 4);
    public static readonly Language German = new(nameof(German), 5);
    public static readonly Language Hebrew = new(nameof(Hebrew), 6);
    public static readonly Language Italian = new(nameof(Italian), 7);
    public static readonly Language Japanese = new(nameof(Japanese), 8);
    public static readonly Language Korean = new(nameof(Korean), 9);
    public static readonly Language Latin = new(nameof(Latin), 10);
    public static readonly Language Phyrexian = new(nameof(Phyrexian), 11);
    public static readonly Language PortugueseBrazil = new(nameof(PortugueseBrazil), 12);
    public static readonly Language Russian = new(nameof(Russian), 13);
    public static readonly Language Sanskrit = new(nameof(Sanskrit), 14);
    public static readonly Language Spanish = new(nameof(Spanish), 15);
    public Language(string name, int value) : base(name, value){}
}
