using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using Humanizer;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace MTG.Objects.SourceGenerator;

[Generator]
public class MtgSetsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register the marker attribute so it's available to the consuming project
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("GenerateSetsAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
        });

        // Find all additional files that match SetList.json
        var setJsonFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith("SetList.json"))
            .Select(static (file, ct) => file.GetText(ct)!.ToString());

        // Find classes with the GenerateSets attribute
        var classesWithAttribute = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "MTG.Objects.SourceGenerator.GenerateSetsAttribute",
                predicate: static (node, _) => true,
                transform: static (ctx, _) => ctx.TargetSymbol)
            .Collect();

        // Combine the JSON and attribute presence
        var combined = setJsonFiles.Combine(classesWithAttribute);

        context.RegisterSourceOutput(combined, static (spc, source) =>
        {
            var (jsonContent, _) = source;
            
            if (string.IsNullOrEmpty(jsonContent))
                return;

            GenerateSets(spc, jsonContent);
        });
    }

    private static void GenerateSets(SourceProductionContext context, string jsonContent)
    {
        try
        {
            using var document = JsonDocument.Parse(jsonContent);
            var root = document.RootElement;

            if (!root.TryGetProperty("data", out var dataArray))
                return;

            var sets = new List<(string Code, string Name)>();

            foreach (var item in dataArray.EnumerateArray())
            {
                if (item.TryGetProperty("code", out var code) &&
                    item.TryGetProperty("name", out var name))
                {
                    sets.Add((code.GetString() ?? string.Empty, name.GetString() ?? string.Empty));
                }
            }

            // Generate SetInfo record
            var setInfoSource = GenerateSetInfoRecord();
            context.AddSource("SetInfo.g.cs", SourceText.From(setInfoSource, Encoding.UTF8));

            // Generate Sets static class
            var setsSource = GenerateSetsClass(sets);
            context.AddSource("Sets.g.cs", SourceText.From(setsSource, Encoding.UTF8));
        }
        catch (JsonException)
        {
            // If JSON parsing fails, report a diagnostic
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "MTG002",
                    "Invalid JSON",
                    "Failed to parse SetList.json file",
                    "MTG.Objects.SourceGenerator",
                    DiagnosticSeverity.Error,
                    true),
                Location.None));
        }
    }

    private static string GenerateSetInfoRecord()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine();
        sb.AppendLine("namespace MTG.Objects.Set");
        sb.AppendLine("{");
        sb.AppendLine($"    [GeneratedCode(\"{typeof(MtgSetsGenerator).FullName}\", \"1.0.0.0\")]");
        sb.AppendLine("    public sealed record SetInfo(string Code, string Name);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateSetsClass(List<(string Code, string Name)> sets)
    {
        var sb = new StringBuilder();
        var seenPropertyNames = new HashSet<string>();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();
        sb.AppendLine("namespace MTG.Objects.Set");
        sb.AppendLine("{");
        sb.AppendLine($"    [GeneratedCode(\"{typeof(MtgSetsGenerator).FullName}\", \"1.0.0.0\")]");
        sb.AppendLine("    public static class Sets");
        sb.AppendLine("    {");

        // Generate static readonly properties for each set
        foreach (var (code, name) in sets.OrderBy(s => s.Code))
        {
            var propertyName = FormatPropertyName(name);
            
            // Handle duplicate property names
            if (seenPropertyNames.Contains(propertyName))
            {
                propertyName = $"{propertyName}_{code}";
            }
            seenPropertyNames.Add(propertyName);

            var escapedName = name.Replace("\\", "\\\\").Replace("\"", "\\\"");
            sb.AppendLine($"        public static readonly SetInfo {propertyName} = new(\"{code}\", \"{escapedName}\");");
        }

        sb.AppendLine();
        sb.AppendLine("        // Lookup dictionary for code-based retrieval");
        sb.AppendLine("        private static readonly Dictionary<string, SetInfo> _byCode = new()");
        sb.AppendLine("        {");

        // Reset for dictionary generation
        seenPropertyNames.Clear();
        
        foreach (var (code, name) in sets.OrderBy(s => s.Code))
        {
            var propertyName = FormatPropertyName(name);
            
            if (seenPropertyNames.Contains(propertyName))
            {
                propertyName = $"{propertyName}_{code}";
            }
            seenPropertyNames.Add(propertyName);

            sb.AppendLine($"            {{ \"{code}\", {propertyName} }},");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        // Lookup dictionary for name-based retrieval");
        sb.AppendLine("        private static readonly Dictionary<string, SetInfo> _byName = new()");
        sb.AppendLine("        {");

        // Reset for name dictionary generation
        seenPropertyNames.Clear();
        
        foreach (var (code, name) in sets.OrderBy(s => s.Code))
        {
            var propertyName = FormatPropertyName(name);
            var escapedName = name.Replace("\\", "\\\\").Replace("\"", "\\\"");
            
            if (seenPropertyNames.Contains(propertyName))
            {
                propertyName = $"{propertyName}_{code}";
            }
            seenPropertyNames.Add(propertyName);

            sb.AppendLine($"            {{ \"{escapedName}\", {propertyName} }},");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        
        // Add utility methods
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Attempts to retrieve set information by set code.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static bool TryGetByCode(string code, out SetInfo? set)");
        sb.AppendLine("            => _byCode.TryGetValue(code, out set);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Attempts to retrieve set information by set name.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static bool TryGetByName(string name, out SetInfo? set)");
        sb.AppendLine("            => _byName.TryGetValue(name, out set);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Gets all available sets.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IEnumerable<SetInfo> All => _byCode.Values;");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Gets all set codes.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IEnumerable<string> AllCodes => _byCode.Keys;");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Gets all set names.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IEnumerable<string> AllNames => _byName.Keys;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string FormatPropertyName(string name)
    {
        // Remove special characters and convert to PascalCase
        var propertyName = name
            .Replace(":", "")
            .Replace("'", "")
            .Replace("'", "")
            .Replace(".", "")
            .Replace(",", "")
            .Replace("-", " ")
            .Replace("(", " ")   // Remove opening parenthesis
            .Replace(")", " ")   // Remove closing parenthesis
            .Replace("&", "And")
            .Replace("/", " ")   // Remove slashes
            .Replace("\"", "")   // Remove quotes
            .Pascalize();

        // Ensure it doesn't start with a digit
        if (propertyName.Length > 0 && char.IsDigit(propertyName[0]))
        {
            propertyName = "_" + propertyName;
        }

        // Remove any remaining invalid characters
        propertyName = System.Text.RegularExpressions.Regex.Replace(propertyName, @"[^\w]", "");

        return propertyName;
    }

    private const string AttributeSource = @"// <auto-generated/>
namespace MTG.Objects.SourceGenerator
{
    /// <summary>
    /// Marker attribute to trigger generation of MTG Sets dictionary from embedded JSON data.
    /// Apply this to a class or assembly to generate the Sets class.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Assembly)]
    public class GenerateSetsAttribute : System.Attribute
    {
    }
}
";
}
