//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Set;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Languages : SmartEnum<Languages> {
    public static readonly Languages AncientGreek = new(nameof(AncientGreek), 0);
    public static readonly Languages Arabic = new(nameof(Arabic), 1);
    public static readonly Languages ChineseSimplified = new(nameof(ChineseSimplified), 2);
    public static readonly Languages ChineseTraditional = new(nameof(ChineseTraditional), 3);
    public static readonly Languages English = new(nameof(English), 4);
    public static readonly Languages French = new(nameof(French), 5);
    public static readonly Languages German = new(nameof(German), 6);
    public static readonly Languages Hebrew = new(nameof(Hebrew), 7);
    public static readonly Languages Italian = new(nameof(Italian), 8);
    public static readonly Languages Japanese = new(nameof(Japanese), 9);
    public static readonly Languages Korean = new(nameof(Korean), 10);
    public static readonly Languages Latin = new(nameof(Latin), 11);
    public static readonly Languages Phyrexian = new(nameof(Phyrexian), 12);
    public static readonly Languages PortugueseBrazil = new(nameof(PortugueseBrazil), 13);
    public static readonly Languages Russian = new(nameof(Russian), 14);
    public static readonly Languages Sanskrit = new(nameof(Sanskrit), 15);
    public static readonly Languages Spanish = new(nameof(Spanish), 16);
    public Languages(string name, int value) : base(name, value){}
}
