//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Set;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Type : SmartEnum<Type> {
    public static readonly Type Alchemy = new(nameof(Alchemy), 0);
    public static readonly Type Archenemy = new(nameof(Archenemy), 1);
    public static readonly Type Arsenal = new(nameof(Arsenal), 2);
    public static readonly Type Box = new(nameof(Box), 3);
    public static readonly Type Commander = new(nameof(Commander), 4);
    public static readonly Type Core = new(nameof(Core), 5);
    public static readonly Type DraftInnovation = new(nameof(DraftInnovation), 6);
    public static readonly Type DuelDeck = new(nameof(DuelDeck), 7);
    public static readonly Type Expansion = new(nameof(Expansion), 8);
    public static readonly Type FromTheVault = new(nameof(FromTheVault), 9);
    public static readonly Type Funny = new(nameof(Funny), 10);
    public static readonly Type Masterpiece = new(nameof(Masterpiece), 11);
    public static readonly Type Masters = new(nameof(Masters), 12);
    public static readonly Type Memorabilia = new(nameof(Memorabilia), 13);
    public static readonly Type Planechase = new(nameof(Planechase), 14);
    public static readonly Type PremiumDeck = new(nameof(PremiumDeck), 15);
    public static readonly Type Promo = new(nameof(Promo), 16);
    public static readonly Type Spellbook = new(nameof(Spellbook), 17);
    public static readonly Type Starter = new(nameof(Starter), 18);
    public static readonly Type Token = new(nameof(Token), 19);
    public static readonly Type TreasureChest = new(nameof(TreasureChest), 20);
    public static readonly Type Vanguard = new(nameof(Vanguard), 21);
    public Type(string name, int value) : base(name, value){}
}
