//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Keywords;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class AbilityWords : SmartEnum<AbilityWords> {
    public static readonly AbilityWords Battalion = new(nameof(Battalion), 0);
    public static readonly AbilityWords Bloodrush = new(nameof(Bloodrush), 1);
    public static readonly AbilityWords Channel = new(nameof(Channel), 2);
    public static readonly AbilityWords Chroma = new(nameof(Chroma), 3);
    public static readonly AbilityWords Cohort = new(nameof(Cohort), 4);
    public static readonly AbilityWords Constellation = new(nameof(Constellation), 5);
    public static readonly AbilityWords Converge = new(nameof(Converge), 6);
    public static readonly AbilityWords Delirium = new(nameof(Delirium), 7);
    public static readonly AbilityWords Domain = new(nameof(Domain), 8);
    public static readonly AbilityWords FatefulHour = new(nameof(FatefulHour), 9);
    public static readonly AbilityWords Ferocious = new(nameof(Ferocious), 10);
    public static readonly AbilityWords Formidable = new(nameof(Formidable), 11);
    public static readonly AbilityWords Grandeur = new(nameof(Grandeur), 12);
    public static readonly AbilityWords Hellbent = new(nameof(Hellbent), 13);
    public static readonly AbilityWords Heroic = new(nameof(Heroic), 14);
    public static readonly AbilityWords Imprint = new(nameof(Imprint), 15);
    public static readonly AbilityWords Inspired = new(nameof(Inspired), 16);
    public static readonly AbilityWords JoinForces = new(nameof(JoinForces), 17);
    public static readonly AbilityWords Kinship = new(nameof(Kinship), 18);
    public static readonly AbilityWords Landfall = new(nameof(Landfall), 19);
    public static readonly AbilityWords Lieutenant = new(nameof(Lieutenant), 20);
    public static readonly AbilityWords Metalcraft = new(nameof(Metalcraft), 21);
    public static readonly AbilityWords Morbid = new(nameof(Morbid), 22);
    public static readonly AbilityWords Parley = new(nameof(Parley), 23);
    public static readonly AbilityWords Radiance = new(nameof(Radiance), 24);
    public static readonly AbilityWords Raid = new(nameof(Raid), 25);
    public static readonly AbilityWords Rally = new(nameof(Rally), 26);
    public static readonly AbilityWords SpellMastery = new(nameof(SpellMastery), 27);
    public static readonly AbilityWords Strive = new(nameof(Strive), 28);
    public static readonly AbilityWords Sweep = new(nameof(Sweep), 29);
    public static readonly AbilityWords TemptingOffer = new(nameof(TemptingOffer), 30);
    public static readonly AbilityWords Threshold = new(nameof(Threshold), 31);
    public static readonly AbilityWords WillOfTheCouncil = new(nameof(WillOfTheCouncil), 32);
    public static readonly AbilityWords Adamant = new(nameof(Adamant), 33);
    public static readonly AbilityWords Addendum = new(nameof(Addendum), 34);
    public static readonly AbilityWords CouncilsDilemma = new(nameof(CouncilsDilemma), 35);
    public static readonly AbilityWords Eminence = new(nameof(Eminence), 36);
    public static readonly AbilityWords Enrage = new(nameof(Enrage), 37);
    public static readonly AbilityWords HerosReward = new(nameof(HerosReward), 38);
    public static readonly AbilityWords Kinfall = new(nameof(Kinfall), 39);
    public static readonly AbilityWords Landship = new(nameof(Landship), 40);
    public static readonly AbilityWords Legacy = new(nameof(Legacy), 41);
    public static readonly AbilityWords Revolt = new(nameof(Revolt), 42);
    public static readonly AbilityWords Underdog = new(nameof(Underdog), 43);
    public static readonly AbilityWords Undergrowth = new(nameof(Undergrowth), 44);
    public static readonly AbilityWords Magecraft = new(nameof(Magecraft), 45);
    public static readonly AbilityWords Teamwork = new(nameof(Teamwork), 46);
    public static readonly AbilityWords PackTactics = new(nameof(PackTactics), 47);
    public static readonly AbilityWords Coven = new(nameof(Coven), 48);
    public static readonly AbilityWords Alliance = new(nameof(Alliance), 49);
    public static readonly AbilityWords Corrupted = new(nameof(Corrupted), 50);
    public AbilityWords(string name, int value) : base(name, value){}
}
