//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.Keywords;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class KeywordActions : SmartEnum<KeywordActions> {
    public static readonly KeywordActions Meld = new(nameof(Meld), 0);
    public static readonly KeywordActions Bolster = new(nameof(Bolster), 1);
    public static readonly KeywordActions Clash = new(nameof(Clash), 2);
    public static readonly KeywordActions Fateseal = new(nameof(Fateseal), 3);
    public static readonly KeywordActions Manifest = new(nameof(Manifest), 4);
    public static readonly KeywordActions Monstrosity = new(nameof(Monstrosity), 5);
    public static readonly KeywordActions Populate = new(nameof(Populate), 6);
    public static readonly KeywordActions Proliferate = new(nameof(Proliferate), 7);
    public static readonly KeywordActions Scry = new(nameof(Scry), 8);
    public static readonly KeywordActions Support = new(nameof(Support), 9);
    public static readonly KeywordActions Detain = new(nameof(Detain), 10);
    public static readonly KeywordActions Explore = new(nameof(Explore), 11);
    public static readonly KeywordActions Fight = new(nameof(Fight), 12);
    public static readonly KeywordActions Amass = new(nameof(Amass), 13);
    public static readonly KeywordActions Adapt = new(nameof(Adapt), 14);
    public static readonly KeywordActions Assemble = new(nameof(Assemble), 15);
    public static readonly KeywordActions Abandon = new(nameof(Abandon), 16);
    public static readonly KeywordActions Activate = new(nameof(Activate), 17);
    public static readonly KeywordActions Attach = new(nameof(Attach), 18);
    public static readonly KeywordActions Seek = new(nameof(Seek), 19);
    public static readonly KeywordActions Cast = new(nameof(Cast), 20);
    public static readonly KeywordActions Counter = new(nameof(Counter), 21);
    public static readonly KeywordActions Create = new(nameof(Create), 22);
    public static readonly KeywordActions Destroy = new(nameof(Destroy), 23);
    public static readonly KeywordActions Discard = new(nameof(Discard), 24);
    public static readonly KeywordActions Double = new(nameof(Double), 25);
    public static readonly KeywordActions Exchange = new(nameof(Exchange), 26);
    public static readonly KeywordActions Exile = new(nameof(Exile), 27);
    public static readonly KeywordActions Investigate = new(nameof(Investigate), 28);
    public static readonly KeywordActions Play = new(nameof(Play), 29);
    public static readonly KeywordActions Regenerate = new(nameof(Regenerate), 30);
    public static readonly KeywordActions Reveal = new(nameof(Reveal), 31);
    public static readonly KeywordActions Sacrifice = new(nameof(Sacrifice), 32);
    public static readonly KeywordActions SetInMotion = new(nameof(SetInMotion), 33);
    public static readonly KeywordActions Shuffle = new(nameof(Shuffle), 34);
    public static readonly KeywordActions Tap = new(nameof(Tap), 35);
    public static readonly KeywordActions Untap = new(nameof(Untap), 36);
    public static readonly KeywordActions Vote = new(nameof(Vote), 37);
    public static readonly KeywordActions Transform = new(nameof(Transform), 38);
    public static readonly KeywordActions Surveil = new(nameof(Surveil), 39);
    public static readonly KeywordActions Goad = new(nameof(Goad), 40);
    public static readonly KeywordActions Planeswalk = new(nameof(Planeswalk), 41);
    public static readonly KeywordActions Mill = new(nameof(Mill), 42);
    public static readonly KeywordActions Learn = new(nameof(Learn), 43);
    public static readonly KeywordActions Conjure = new(nameof(Conjure), 44);
    public static readonly KeywordActions Exert = new(nameof(Exert), 45);
    public static readonly KeywordActions Connive = new(nameof(Connive), 46);
    public static readonly KeywordActions VentureIntoTheDungeon = new(nameof(VentureIntoTheDungeon), 47);
    public static readonly KeywordActions Convert = new(nameof(Convert), 48);
    public static readonly KeywordActions OpenAnAttraction = new(nameof(OpenAnAttraction), 49);
    public static readonly KeywordActions RollToVisitYourAttractions = new(nameof(RollToVisitYourAttractions), 50);
    public KeywordActions(string name, int value) : base(name, value){}
}
