//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.TcgplayerSkus;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Conditions : SmartEnum<Conditions> {
    public static readonly Conditions NEARMINT = new(nameof(NEARMINT), 0);
    public static readonly Conditions LIGHTLYPLAYED = new(nameof(LIGHTLYPLAYED), 1);
    public static readonly Conditions MODERATELYPLAYED = new(nameof(MODERATELYPLAYED), 2);
    public static readonly Conditions HEAVILYPLAYED = new(nameof(HEAVILYPLAYED), 3);
    public static readonly Conditions DAMAGED = new(nameof(DAMAGED), 4);
    public static readonly Conditions UNOPENED = new(nameof(UNOPENED), 5);
    public Conditions(string name, int value) : base(name, value){}
}
