//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.TcgplayerSkus;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Finishes : SmartEnum<Finishes> {
    public static readonly Finishes FOILETCHED = new(nameof(FOILETCHED), 0);
    public Finishes(string name, int value) : base(name, value){}
}
