//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.TcgplayerSkus;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Languages : SmartEnum<Languages> {
    public static readonly Languages ENGLISH = new(nameof(ENGLISH), 0);
    public static readonly Languages CHINESESIMPLIFIED = new(nameof(CHINESESIMPLIFIED), 1);
    public static readonly Languages CHINESETRADITIONAL = new(nameof(CHINESETRADITIONAL), 2);
    public static readonly Languages FRENCH = new(nameof(FRENCH), 3);
    public static readonly Languages GERMAN = new(nameof(GERMAN), 4);
    public static readonly Languages ITALIAN = new(nameof(ITALIAN), 5);
    public static readonly Languages JAPANESE = new(nameof(JAPANESE), 6);
    public static readonly Languages KOREAN = new(nameof(KOREAN), 7);
    public static readonly Languages PORTUGUESEBRAZIL = new(nameof(PORTUGUESEBRAZIL), 8);
    public static readonly Languages RUSSIAN = new(nameof(RUSSIAN), 9);
    public static readonly Languages SPANISH = new(nameof(SPANISH), 10);
    public Languages(string name, int value) : base(name, value){}
}
