//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.TcgplayerSkus;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Language : SmartEnum<Language> {
    public static readonly Language ENGLISH = new(nameof(ENGLISH), 0);
    public static readonly Language CHINESESIMPLIFIED = new(nameof(CHINESESIMPLIFIED), 1);
    public static readonly Language CHINESETRADITIONAL = new(nameof(CHINESETRADITIONAL), 2);
    public static readonly Language FRENCH = new(nameof(FRENCH), 3);
    public static readonly Language GERMAN = new(nameof(GERMAN), 4);
    public static readonly Language ITALIAN = new(nameof(ITALIAN), 5);
    public static readonly Language JAPANESE = new(nameof(JAPANESE), 6);
    public static readonly Language KOREAN = new(nameof(KOREAN), 7);
    public static readonly Language PORTUGUESEBRAZIL = new(nameof(PORTUGUESEBRAZIL), 8);
    public static readonly Language RUSSIAN = new(nameof(RUSSIAN), 9);
    public static readonly Language SPANISH = new(nameof(SPANISH), 10);
    public Language(string name, int value) : base(name, value){}
}
