//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.TcgplayerSkus;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Printings : SmartEnum<Printings> {
    public static readonly Printings NONFOIL = new(nameof(NONFOIL), 0);
    public static readonly Printings FOIL = new(nameof(FOIL), 1);
    public Printings(string name, int value) : base(name, value){}
}
