//------------------
//<auto-generated />
//------------------

using System.CodeDom.Compiler;

namespace MTG.Objects.Enum.TcgplayerSkus;

[GeneratedCode("MTG.Object.Generator.Modules.EnumGenerator.Services.EnumCodeGenerator", "1.0.0.0")]
public sealed class Printing : SmartEnum<Printing> {
    public static readonly Printing NONFOIL = new(nameof(NONFOIL), 0);
    public static readonly Printing FOIL = new(nameof(FOIL), 1);
    public Printing(string name, int value) : base(name, value){}
}
